
CREATE TABLE daysofweek (
"id" INTEGER NOT NULL CONSTRAINT "[PK_NAME]" PRIMARY KEY AUTOINCREMENT,
"dayname" NVARCHAR(10) NOT NULL UNIQUE,
"daynumber" INTEGER NOT NULL UNIQUE,
, datevalue DATETIME NOT NULL UNIQUE);
