CREATE TABLE "account" (
"id" INTEGER NOT NULL CONSTRAINT "[PK_NAME]" PRIMARY KEY AUTOINCREMENT,
"contact_id" INTEGER REFERENCES contact(contactid),
"vehicletype" NVARCHAR(20) NOT NULL,
"password" TEXT NOT NULL,
 "salt" TEXT NOT NULL UNIQUE,
 "passwordhash" TEXT NOT NULL UNIQUE,
  "isactive" BOOLEAN DEFAULT 1,
  "isblocked" BOOLEAN DEFAULT 0);