#github action to deployy  smart asp.net hosting
name: Deploy API to Smart ASP.NET.NET Hosting
on:
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # specify the .NET version

      - name: Restore dependencies
        run: dotnet restore ./TG.CarParkEsher/TG.CarParkEsher.Booking/TG.CarParkEsher.Booking.csproj

      - name: Build the project
        run: dotnet build  ./TG.CarParkEsher/TG.CarParkEsher.Booking/TG.CarParkEsher.Booking.csproj --configuration Release --no-restore

 


 